services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: habis-finance-api:latest
    container_name: habis-finance-api
    restart: unless-stopped
    expose:
      - "8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.habis-finance-api.rule=Host(`api.abbisapps.site`)
      - traefik.http.routers.habis-finance-api.entrypoints=websecure
      - traefik.http.routers.habis-finance-api.tls=true
      - traefik.http.routers.habis-finance-api.tls.certresolver=letsencrypt
      - traefik.http.services.habis-finance-api.loadbalancer.server.port=8000

networks:
  proxy:
    external: true
