<?php

declare(strict_types=1);

return [
    'auth' => [
        'login' => [
            'max_attempts' => (int) env('AUTH_LOGIN_MAX_ATTEMPTS', 5),
            'decay_minutes' => (int) env('AUTH_LOGIN_DECAY_MINUTES', 1),
        ],
        'register' => [
            'max_attempts' => (int) env('AUTH_REGISTER_MAX_ATTEMPTS', 3),
            'decay_minutes' => (int) env('AUTH_REGISTER_DECAY_MINUTES', 1),
        ],
        'activation' => [
            'max_attempts' => (int) env('AUTH_ACTIVATION_MAX_ATTEMPTS', 5),
            'decay_minutes' => (int) env('AUTH_ACTIVATION_DECAY_MINUTES', 1),
        ],
        'registration' => [
            'enabled' => (bool) env('AUTH_REGISTRATION_ENABLED', false),
        ],
        'token_ttl_minutes' => (int) env('AUTH_TOKEN_TTL_MINUTES', 1440),
        'token_abilities' => [
            'access-api',
        ],
    ],
    'idempotency' => [
        'ttl_minutes' => (int) env('IDEMPOTENCY_TTL_MINUTES', 1440),
        'bypass_persistence_paths' => [
            'api/v1/login',
            'api/v1/activate',
            'api/v1/activation/resend',
            'api/v1/batch-runs',
        ],
    ],
    'otp' => [
        'expires_minutes' => (int) env('OTP_EXPIRES_MINUTES', 10),
        'max_attempts' => (int) env('OTP_MAX_ATTEMPTS', 5),
        'resend_decay_minutes' => (int) env('OTP_RESEND_DECAY_MINUTES', 1),
        'delivery_max_attempts' => (int) env('OTP_DELIVERY_MAX_ATTEMPTS', 3),
        'require_email_delivery' => (bool) env('OTP_REQUIRE_EMAIL_DELIVERY', true),
        'delivery_channels' => [
            'sms',
            'email',
        ],
        'delivery_provider' => env('OTP_DELIVERY_PROVIDER', 'log'),
        'http_sms' => [
            'endpoint' => env('OTP_HTTP_SMS_ENDPOINT'),
            'token' => env('OTP_HTTP_SMS_TOKEN'),
            'sender' => env('OTP_HTTP_SMS_SENDER', 'HABIS'),
            'timeout_seconds' => (int) env('OTP_HTTP_SMS_TIMEOUT_SECONDS', 10),
        ],
        'email_provider' => env('OTP_EMAIL_PROVIDER', 'mail'),
    ],
    'bootstrap_admin' => [
        'enabled' => (bool) env('SEED_BOOTSTRAP_ADMIN', false),
        'email' => env('SEED_BOOTSTRAP_ADMIN_EMAIL'),
        'phone' => env('SEED_BOOTSTRAP_ADMIN_PHONE'),
        'name' => env('SEED_BOOTSTRAP_ADMIN_NAME'),
        'password' => env('SEED_BOOTSTRAP_ADMIN_PASSWORD'),
        'role' => env('SEED_BOOTSTRAP_ADMIN_ROLE', 'platform-admin'),
    ],
    'crm' => [
        'kyc' => [
            'enforce_maker_checker' => (bool) env('CRM_KYC_ENFORCE_MAKER_CHECKER', true),
        ],
    ],
    'accounting_day' => [
        // Transitional safety for legacy test flows while financial suites are
        // migrated to explicit open-day setup (JC-012). In production this
        // should stay disabled.
        'auto_open_on_missing' => (bool) env('ACCOUNTING_DAY_AUTO_OPEN_ON_MISSING', false),
    ],
    'permissions' => [
        /*
         * When false (default), protected permissions (PII, KYC verification,
         * institution scope, etc.) can only be granted to platform-admin.
         * When true, a role editor may delegate the delegable subset of
         * protected permissions to non-platform roles; the institution-control
         * floor (see RoleController::nonDelegableProtectedPermissions) is never
         * delegable regardless of this flag.
         */
        'allow_protected_delegation' => env('SECURITY_ALLOW_PROTECTED_DELEGATION', false),

        'roles' => [
            'platform-admin' => [
                'system.view-health',
                'audit.view',
                'agencies.view',
                'agencies.manage',
                'users.view',
                'users.create',
                'users.manage',
                'users.update',
                'users.status.manage',
                'roles.manage',
                'roles.view',
                'users.roles.manage',
                'staff.assignments.view',
                'staff.assignments.manage',
                'batch.procedures.view',
                'batch.procedures.manage',
                'batch.runs.view',
                'batch.runs.manage',
                'accounting.days.view',
                'accounting.days.open',
                'accounting.days.close',
                'accounting.days.reopen',
                'accounting.calendar.view',
                'accounting.calendar.manage',
                'documents.view',
                'documents.create',
                'documents.archive',
                'references.reserve',
                'crm.scope.institution.read',
                'crm.scope.institution.review',
                'crm.scope.institution.manage',
                'crm.pii.view',
                'crm.reviews.view',
                'crm.kyc.override.expired_identity',
                'crm.kyc.override.self_verify',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.clients.archive',
                'crm.kyc.submit',
                'crm.kyc.review',
                'crm.kyc.verify',
                'crm.kyc.reject',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.identity_documents.archive',
                'crm.identity_documents.verify',
                'crm.identity_documents.reject',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.guarantors.archive',
                'crm.guarantors.verify',
                'crm.guarantors.reject',
                'crm.guarantors.pii.view',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'crm.proxies.archive',
                'crm.proxies.verify',
                'crm.proxies.reject',
                'crm.proxies.expire',
                'account.products.view',
                'account.products.create',
                'account.products.update',
                'account.products.archive',
                'emf.accounts.view',
                'emf.accounts.create',
                'emf.accounts.update',
                'emf.accounts.archive',
                'emf.mappings.view',
                'emf.mappings.create',
                'emf.mappings.update',
                'emf.mappings.archive',
                'operation.codes.view',
                'operation.codes.create',
                'operation.codes.update',
                'operation.codes.archive',
                'operation.mappings.view',
                'operation.mappings.create',
                'operation.mappings.update',
                'operation.mappings.archive',
                'ledger.accounts.view',
                'ledger.accounts.create',
                'ledger.accounts.update',
                'ledger.accounts.archive',
                'customer.accounts.view',
                'customer.accounts.balance.view',
                'customer.accounts.statement.view',
                'customer.accounts.create',
                'customer.accounts.update',
                'customer.accounts.close',
                'customer.account-signatures.view',
                'customer.account-signatures.create',
                'customer.account-signatures.verify',
                'customer.account-signatures.revoke',
                'account.holds.view',
                'account.holds.create',
                'account.holds.update',
                'account.holds.release',
                'account.holds.archive',
                'journal.entries.view',
                'journal.entries.create',
                'journal.entries.update',
                'journal.entries.archive',
                'journal.entries.review',
                'journal.entries.post',
                'journal.entries.reverse',
                'journal.lines.view',
                'journal.lines.create',
                'journal.lines.update',
                'journal.lines.archive',
                'loan.products.view',
                'loan.products.create',
                'loan.products.update',
                'loan.products.archive',
                'loans.view',
                'loans.create',
                'loans.update',
                'loans.approvals.montage',
                'loans.approvals.comptabilite',
                'loans.approvals.controle',
                'loans.approvals.direction',
                'loans.disburse',
                'loans.repayments.create',
                'loans.early-repayments.create',
                'loans.status.transition',
                'loans.schedules.generate',
                'loans.schedules.reschedule',
                'loans.collaterals.manage',
                'loans.guarantees.manage',
                'loans.delinquency.manage',
                'loans.transfers.manage',
                'loans.recoveries.manage',
                'sectors.view',
                'sectors.create',
                'sectors.update',
                'sectors.archive',
                'sub-sectors.view',
                'sub-sectors.create',
                'sub-sectors.update',
                'sub-sectors.archive',
                'cash.denominations.view',
                'cash.denominations.manage',
                'cash.tills.view',
                'cash.tills.manage',
                'cash.sessions.view',
                'cash.sessions.manage',
                'cash.transactions.view',
                'cash.transactions.manage',
                'cash.transactions.reverse',
                'cash.transactions.reverse.self_override',
                'cash.reconciliations.view',
                'cash.reconciliations.manage',
                'hr.employee.manage',
                'hr.salary.view',
                'insurance.products.manage',
                'insurance.subscriptions.create',
                'insurance.subscriptions.manage',
                'insurance.premiums.manage',
                'insurance.premiums.collect',
                'insurance.claims.intake',
                'insurance.claims.review',
                'insurance.claims.settle',
                'insurance.remittances.manage',
                'insurance.reversals.manage',
                'insurance.reports.view',
                'insurance.reports.export',
                'accounting.audit.view',
                'islamic.standards.view',
                'islamic.standards.create',
                'islamic.standards.update',
                'islamic.standards.activate',
                'islamic.standards.retire',
                'islamic.standards.link',
                'islamic.regulatory_signoffs.view',
                'islamic.regulatory_signoffs.create',
                'islamic.regulatory_signoffs.update',
                'islamic.regulatory_signoffs.activate',
                'islamic.regulatory_signoffs.suspend',
                'islamic.regulatory_signoffs.revoke',
                'islamic.regulatory_signoffs.retire',
                'islamic.regulatory_signoffs.link',
                'islamic.sharia_authorities.view',
                'islamic.sharia_authorities.create',
                'islamic.sharia_authorities.update',
                'islamic.sharia_authorities.activate',
                'islamic.sharia_authorities.retire',
                'islamic.sharia_authorities.members.manage',
                'islamic.sharia.decisions.review',
                'islamic.sharia.decisions.approve',
            ],
            // Deprecated compatibility alias for agency-scoped staff administration.
            // New grants should use agency-manager.
            'user-admin' => [
                'users.view',
                'users.create',
                'users.update',
                'users.status.manage',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.kyc.submit',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'account.products.view',
                'emf.accounts.view',
                'emf.mappings.view',
                'operation.codes.view',
                'operation.mappings.view',
                'ledger.accounts.view',
                'ledger.scope.institution.read',
                'customer.accounts.view',
                'customer.accounts.balance.view',
                'customer.account-signatures.view',
                'account.holds.view',
                'journal.entries.view',
                'journal.lines.view',
                'loan.products.view',
                'loans.view',
                'sectors.view',
                'sub-sectors.view',
                'cash.denominations.view',
                'cash.tills.view',
                'cash.sessions.view',
                'cash.transactions.view',
                'cash.reconciliations.view',
            ],
            'agency-manager' => [
                'agencies.view',
                'users.view',
                'users.create',
                'users.update',
                'users.status.manage',
                'staff.assignments.view',
                'staff.assignments.manage',
                'batch.runs.view',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.kyc.submit',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'account.products.view',
                'emf.accounts.view',
                'emf.mappings.view',
                'operation.codes.view',
                'operation.mappings.view',
                'ledger.accounts.view',
                'customer.accounts.view',
                'customer.accounts.balance.view',
                'customer.account-signatures.view',
                'account.holds.view',
                'journal.entries.view',
                'journal.lines.view',
                'accounting.days.view',
                'accounting.days.open',
                'accounting.days.close',
                'accounting.calendar.view',
                'loan.products.view',
                'loans.view',
                'loans.create',
                'loans.update',
                'loans.approvals.montage',
                'loans.approvals.direction',
                'loans.disburse',
                'loans.repayments.create',
                'loans.early-repayments.create',
                'loans.arrears.assess',
                'loans.scope.institution.read',
                'loans.guarantees.manage',
                'loans.delinquency.manage',
                'loans.transfers.manage',
                'loans.recoveries.manage',
                'sectors.view',
                'sub-sectors.view',
                'cash.denominations.view',
                'cash.tills.view',
                'cash.tills.manage',
                'cash.sessions.view',
                'cash.sessions.manage',
                'cash.transactions.view',
                'cash.transactions.manage',
                'cash.transactions.reverse',
                'cash.transactions.reverse.self_override',
                'cash.reconciliations.view',
                'cash.reconciliations.manage',
                'insurance.subscriptions.create',
                'insurance.subscriptions.manage',
                'insurance.premiums.manage',
                'insurance.premiums.collect',
                'insurance.claims.intake',
                'insurance.claims.review',
                'insurance.remittances.manage',
                'insurance.reports.view',
                'insurance.reports.export',
            ],
            'regional-manager' => [
                'users.view',
                'agencies.view',
                'documents.view',
                'references.reserve',
                'crm.scope.institution.read',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.identity_documents.view',
                'crm.guarantors.view',
                'crm.proxies.view',
                'loan.products.view',
                'loans.view',
                'loans.scope.institution.read',
                'cash.denominations.view',
                'cash.tills.view',
                'cash.sessions.view',
                'cash.transactions.view',
                'cash.reconciliations.view',
                'accounting.days.view',
                'accounting.calendar.view',
            ],
            'teller' => [
                'system.view-health',
                'agencies.view',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.identity.view',
                'customer.accounts.view',
                'customer.accounts.balance.view',
                'cash.denominations.view',
                'cash.tills.view',
                'cash.sessions.view',
                'cash.sessions.manage',
                'cash.transactions.view',
                'cash.transactions.manage',
                'cash.reconciliations.view',
                'cash.reconciliations.manage',
                'accounting.days.view',
            ],
            'loan-officer' => [
                'system.view-health',
                'agencies.view',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.identity_documents.view',
                'crm.guarantors.view',
                'crm.proxies.view',
                'customer.accounts.view',
                'customer.accounts.balance.view',
                'loan.products.view',
                'loans.view',
                'loans.create',
                'loans.update',
                'loans.approvals.montage',
                'loans.guarantees.manage',
                'loans.delinquency.manage',
                'cash.denominations.view',
                'cash.tills.view',
                'accounting.days.view',
            ],
            'accountant' => [
                'system.view-health',
                'audit.view',
                'accounting.days.view',
                'accounting.days.open',
                'accounting.days.close',
                'accounting.calendar.view',
                'accounting.calendar.manage',
                'agencies.view',
                'documents.view',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.identity.view',
                'customer.accounts.view',
                'customer.accounts.balance.view',
                'loans.view',
                'loans.approvals.comptabilite',
                'loans.disburse',
                'loans.repayments.create',
                'loans.early-repayments.create',
                'loans.arrears.assess',
                'loans.recoveries.manage',
            ],
            'kyc-officer' => [
                'system.view-health',
                'agencies.view',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.pii.view',
                'crm.reviews.view',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.clients.archive',
                'crm.kyc.submit',
                'crm.kyc.review',
                'crm.kyc.verify',
                'crm.kyc.reject',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.identity_documents.archive',
                'crm.identity_documents.verify',
                'crm.identity_documents.reject',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.guarantors.archive',
                'crm.guarantors.verify',
                'crm.guarantors.reject',
                'crm.guarantors.pii.view',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'crm.proxies.archive',
                'crm.proxies.verify',
                'crm.proxies.reject',
                'crm.proxies.expire',
                'ledger.accounts.view',
                'customer.accounts.view',
                'customer.accounts.balance.view',
                'customer.account-signatures.view',
                'customer.account-signatures.create',
                'customer.account-signatures.verify',
                'customer.account-signatures.revoke',
                'account.holds.view',
                'journal.entries.view',
                'journal.lines.view',
                'loan.products.view',
                'loans.view',
                'sectors.view',
                'sub-sectors.view',
            ],
            'compliance-officer' => [
                'system.view-health',
                'audit.view',
                'agencies.view',
                'documents.view',
                'crm.scope.institution.read',
                'crm.scope.institution.review',
                'crm.pii.view',
                'crm.reviews.view',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.kyc.review',
                'crm.kyc.verify',
                'crm.kyc.reject',
                'crm.identity_documents.view',
                'crm.identity_documents.verify',
                'crm.identity_documents.reject',
                'crm.guarantors.view',
                'crm.guarantors.verify',
                'crm.guarantors.reject',
                'crm.proxies.view',
                'crm.proxies.verify',
                'crm.proxies.reject',
                'accounting.audit.view',
                'accounting.days.view',
                'accounting.calendar.view',
                'loans.view',
                'loans.approvals.controle',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'auditor' => [
                'system.view-health',
                'audit.view',
                'agencies.view',
                'users.view',
                'documents.view',
                'crm.scope.institution.read',
                'crm.clients.view',
                'crm.clients.identity.view',
                'crm.identity_documents.view',
                'crm.guarantors.view',
                'crm.proxies.view',
                'crm.reviews.view',
                'accounting.audit.view',
                'accounting.days.view',
                'accounting.calendar.view',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'staff' => [
                'system.view-health',
                'agencies.view',
            ],
        ],
    ],
    'audit' => [
        'log_name' => 'default',
        'actor_fallback' => 'system',
    ],
    'documents' => [
        'backfill' => [
            'allowed_source_disks' => array_values(array_filter(array_map(
                static fn (string $disk): string => trim($disk),
                explode(',', (string) env('DOCUMENT_BACKFILL_ALLOWED_SOURCE_DISKS', 'local'))
            ), static fn (string $disk): bool => $disk !== '')),
        ],
    ],
];
