<?php

declare(strict_types=1);

return [
    'auth' => [
        'login' => [
            'max_attempts' => (int) env('AUTH_LOGIN_MAX_ATTEMPTS', 5),
            'decay_minutes' => (int) env('AUTH_LOGIN_DECAY_MINUTES', 1),
        ],
        'register' => [
            'max_attempts' => (int) env('AUTH_REGISTER_MAX_ATTEMPTS', 3),
            'decay_minutes' => (int) env('AUTH_REGISTER_DECAY_MINUTES', 1),
        ],
        'activation' => [
            'max_attempts' => (int) env('AUTH_ACTIVATION_MAX_ATTEMPTS', 5),
            'decay_minutes' => (int) env('AUTH_ACTIVATION_DECAY_MINUTES', 1),
        ],
        'registration' => [
            'enabled' => (bool) env('AUTH_REGISTRATION_ENABLED', false),
        ],
        'token_ttl_minutes' => (int) env('AUTH_TOKEN_TTL_MINUTES', 60),
        'token_abilities' => [
            'access-api',
        ],
    ],
    'idempotency' => [
        'ttl_minutes' => (int) env('IDEMPOTENCY_TTL_MINUTES', 1440),
        'bypass_persistence_paths' => [
            'api/v1/login',
            'api/v1/activate',
            'api/v1/activation/resend',
            'api/v1/batch-runs',
        ],
    ],
    'otp' => [
        'expires_minutes' => (int) env('OTP_EXPIRES_MINUTES', 10),
        'max_attempts' => (int) env('OTP_MAX_ATTEMPTS', 5),
        'resend_decay_minutes' => (int) env('OTP_RESEND_DECAY_MINUTES', 1),
        'delivery_channels' => [
            'sms',
            'email',
        ],
        'delivery_provider' => env('OTP_DELIVERY_PROVIDER', 'log'),
    ],
    'permissions' => [
        'roles' => [
            'platform-admin' => [
                'system.view-health',
                'audit.view',
                'agencies.view',
                'agencies.manage',
                'users.view',
                'users.create',
                'users.manage',
                'users.update',
                'users.status.manage',
                'roles.manage',
                'roles.view',
                'users.roles.manage',
                'staff.assignments.view',
                'staff.assignments.manage',
                'batch.procedures.view',
                'batch.procedures.manage',
                'batch.runs.view',
                'batch.runs.manage',
                'documents.view',
                'documents.create',
                'documents.archive',
                'references.reserve',
                'crm.scope.institution.read',
                'crm.scope.institution.review',
                'crm.scope.institution.manage',
                'crm.pii.view',
                'crm.reviews.view',
                'crm.kyc.override.expired_identity',
                'crm.kyc.override.self_verify',
                'crm.clients.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.clients.archive',
                'crm.kyc.submit',
                'crm.kyc.review',
                'crm.kyc.verify',
                'crm.kyc.reject',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.identity_documents.archive',
                'crm.identity_documents.verify',
                'crm.identity_documents.reject',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.guarantors.archive',
                'crm.guarantors.verify',
                'crm.guarantors.reject',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'crm.proxies.archive',
                'crm.proxies.verify',
                'crm.proxies.reject',
                'crm.proxies.expire',
                'ledger.accounts.view',
                'ledger.accounts.create',
                'ledger.accounts.update',
                'ledger.accounts.archive',
                'customer.accounts.view',
                'customer.accounts.create',
                'customer.accounts.update',
                'customer.accounts.close',
                'account.holds.view',
                'account.holds.create',
                'account.holds.update',
                'account.holds.release',
                'account.holds.archive',
                'journal.entries.view',
                'journal.entries.create',
                'journal.entries.update',
                'journal.entries.archive',
                'journal.entries.review',
                'journal.entries.reverse',
                'journal.lines.view',
                'journal.lines.create',
                'journal.lines.update',
                'journal.lines.archive',
                'sectors.view',
                'sectors.create',
                'sectors.update',
                'sectors.archive',
                'sub-sectors.view',
                'sub-sectors.create',
                'sub-sectors.update',
                'sub-sectors.archive',
                'cash.denominations.view',
                'cash.denominations.manage',
                'cash.tills.view',
                'cash.tills.manage',
                'accounting.audit.view',
            ],
            // Deprecated compatibility alias for agency-scoped staff administration.
            // New grants should use agency-manager.
            'user-admin' => [
                'users.view',
                'users.create',
                'users.update',
                'users.status.manage',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.kyc.submit',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'ledger.accounts.view',
                'customer.accounts.view',
                'account.holds.view',
                'journal.entries.view',
                'journal.lines.view',
                'sectors.view',
                'sub-sectors.view',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'agency-manager' => [
                'agencies.view',
                'users.view',
                'users.create',
                'users.update',
                'users.status.manage',
                'staff.assignments.view',
                'staff.assignments.manage',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.kyc.submit',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'ledger.accounts.view',
                'customer.accounts.view',
                'account.holds.view',
                'journal.entries.view',
                'journal.lines.view',
                'sectors.view',
                'sub-sectors.view',
                'cash.denominations.view',
                'cash.tills.view',
                'cash.tills.manage',
            ],
            'regional-manager' => [
                'users.view',
                'agencies.view',
                'documents.view',
                'references.reserve',
                'crm.scope.institution.read',
                'crm.clients.view',
                'crm.identity_documents.view',
                'crm.guarantors.view',
                'crm.proxies.view',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'teller' => [
                'system.view-health',
                'agencies.view',
                'documents.view',
                'documents.create',
                'references.reserve',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'loan-officer' => [
                'system.view-health',
                'agencies.view',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.clients.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.identity_documents.view',
                'crm.guarantors.view',
                'crm.proxies.view',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'accountant' => [
                'system.view-health',
                'audit.view',
                'agencies.view',
                'documents.view',
                'references.reserve',
            ],
            'kyc-officer' => [
                'system.view-health',
                'agencies.view',
                'documents.view',
                'documents.create',
                'references.reserve',
                'crm.pii.view',
                'crm.reviews.view',
                'crm.clients.view',
                'crm.clients.create',
                'crm.clients.update',
                'crm.clients.archive',
                'crm.kyc.submit',
                'crm.kyc.review',
                'crm.kyc.verify',
                'crm.kyc.reject',
                'crm.identity_documents.view',
                'crm.identity_documents.create',
                'crm.identity_documents.update',
                'crm.identity_documents.archive',
                'crm.identity_documents.verify',
                'crm.identity_documents.reject',
                'crm.guarantors.view',
                'crm.guarantors.create',
                'crm.guarantors.update',
                'crm.guarantors.archive',
                'crm.guarantors.verify',
                'crm.guarantors.reject',
                'crm.proxies.view',
                'crm.proxies.create',
                'crm.proxies.update',
                'crm.proxies.archive',
                'crm.proxies.verify',
                'crm.proxies.reject',
                'crm.proxies.expire',
                'ledger.accounts.view',
                'customer.accounts.view',
                'account.holds.view',
                'journal.entries.view',
                'journal.lines.view',
                'sectors.view',
                'sub-sectors.view',
            ],
            'compliance-officer' => [
                'system.view-health',
                'audit.view',
                'agencies.view',
                'documents.view',
                'crm.scope.institution.read',
                'crm.scope.institution.review',
                'crm.pii.view',
                'crm.reviews.view',
                'crm.clients.view',
                'crm.kyc.review',
                'crm.kyc.verify',
                'crm.kyc.reject',
                'crm.identity_documents.view',
                'crm.identity_documents.verify',
                'crm.identity_documents.reject',
                'crm.guarantors.view',
                'crm.guarantors.verify',
                'crm.guarantors.reject',
                'crm.proxies.view',
                'crm.proxies.verify',
                'crm.proxies.reject',
                'accounting.audit.view',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'auditor' => [
                'system.view-health',
                'audit.view',
                'agencies.view',
                'users.view',
                'documents.view',
                'crm.scope.institution.read',
                'crm.clients.view',
                'crm.identity_documents.view',
                'crm.guarantors.view',
                'crm.proxies.view',
                'crm.reviews.view',
                'accounting.audit.view',
                'cash.denominations.view',
                'cash.tills.view',
            ],
            'staff' => [
                'system.view-health',
                'agencies.view',
            ],
        ],
    ],
    'audit' => [
        'log_name' => 'default',
        'actor_fallback' => 'system',
    ],
    'documents' => [
        'backfill' => [
            'allowed_source_disks' => array_values(array_filter(array_map(
                static fn (string $disk): string => trim($disk),
                explode(',', (string) env('DOCUMENT_BACKFILL_ALLOWED_SOURCE_DISKS', 'local'))
            ))),
        ],
    ],
];
